print('Que bom que recebeu um aumento! Vamos ver quanto recebe agora.')
print()
sal = int(input('Quanto você recebia? '))
print()
aumento = int(input('E teve aumento de quanto em %? '))
print()
novosal = (sal + sal*aumento/100)
print('seu novo salário é ')
print("%.2f" % novosal)
print()
print('parabéns!')
