print()
print('Vamos calcular o valor do aluguel de um veiculo por alguns dias.')
print()
d = int(input('Quantos dias ficou com o veículo? '))
print()
km = int(input('E quantos km rodou? '))
total = (d*60) + (hm*15/100)
print()
print('O valor a ser pago é de:')
print()
print(total)
